#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "psd-covert"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]

[limits]
cpu_ms = 50000 # increased for heavy PSD parsing (plan permitting)
memory_mb = 1024

[assets]
directory = "./view-build"
binding = "ASSETS"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[rules]]
type = "Text"
globs = [ "**/*.sql" ]
fallthrough = true