#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "psd-covert"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "alfanet"

[limits]
cpu_ms = 50000
memory_mb = 1024

[assets]
directory = "./view-build"
binding = "ASSETS"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[[migrations]]
tag = "v2"
new_classes = [ "UploadCoordinator" ]

[[migrations]]
tag = "v3"
new_classes = [ "PsdWorkflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"

[[durable_objects.bindings]]
name = "UPLOAD_COORDINATOR_DO"
class_name = "UploadCoordinator"

[[durable_objects.bindings]]
name = "PSD_WORKFLOW_DO"
class_name = "PsdWorkflow"

[[r2_buckets]]
binding = "PSD_UPLOADS"
bucket_name = "psd-uploads"

[build]
command = "npm run build"  # if you have a build script
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
main = "main.ts"
dir = "."
rules = [
  { type = "Text", globs = ["**/*.sql"], fallthrough = true }
]
workspace = "alfanet"
bindings = []