#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "psd-covert"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./view-build"
binding = "ASSETS"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
